# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: employee_development
  
  pool: 5
  username: root
  password: root

staging:
  <<: *default
  database: employee_development
  
  pool: 5
  username: root
  password: root

production:
  <<: *default
  database: employee_development
  
  pool: 5
  username: root
  password: root
